version: "3.9"

volumes:
    localtimescaledb:
    localgrafana:


services:

    timescaledb:
        image: timescale/timescaledb:latest-pg14
        user: postgres
        environment:
            - POSTGRES_PASSWORD=ShouldB3Secre1Ss0d0Something
            - POSTGRES_DB=AnuGQC
            - TIMESCALEDB_TELEMETRY=off
            - PGDATA=/var/lib/postgresql/data/pgdata
            # - TS_TUNE_NUM_CPUS=4
            # - TS_TUNE_MEMORY=4GB
            # - TS_TUNE_MAX_CONNS=200
        ports:
            - "5432:5432"
        volumes:
            - ./initdb/10-gnss_qc_summary.sql:/docker-entrypoint-initdb.d/10-gnss_qc_summary.sql
            - type: volume
              source: localtimescaledb # Update this to an appropriate path
              target: /var/lib/postgresql/data
        logging:
            driver: "local"
            options:
                max-file: "10"
                max-size: "10m"
        restart: unless-stopped

    grafana:
        image: grafana/grafana
            # environment:
            #     - GF_INSTALL_PLUGINS=
        environment:
            - GF_SECURITY_ADMIN_USER=admin
            - GF_SECURITY_ADMIN_PASSWORD=Ev3nM0reSecretYouKn0w
            - GF_USERS_ALLOW_SIGN_UP=false
        depends_on:
            - timescaledb
        ports:
            - "3000:3000"
        volumes:
            - type: bind
              source: ./initgrafana
              target: /etc/grafana/provisioning
              read_only: true
            - type: volume
              source: localgrafana # Update this to an appropriate path
              target: /var/lib/grafana
        logging:
            driver: "local"
            options:
                max-file: "10"
                max-size: "10m"
        restart: unless-stopped

    ingest:
        build:
            context: .
            dockerfile: Dockerfile-ingest
        depends_on:
            - timescaledb
        volumes:
            - type: bind
              source: ./config
              target: /app/config
            - type: bind
              source: ./testdata
              target: /app/qcdata
        logging:
            driver: "local"
            options:
                max-file: "10"
                max-size: "10m"
        restart: unless-stopped
